## ndarray
- np.array로 활용 배열 생성
- **하나의 데이터 타입** 만 배열에 넣을 수 있음 (C처럼)

차례대로 데이터가 메모리에 들어감 (붙어있음) > 메모리의 접근성이 좋음

메모리에 들어가는 게 일정해서 좋음

In [3]:
import numpy as np

In [4]:
#다 다른 타입을 넣어도 자동 형변환 일어남
test_array = np.array(["1", 4.0, 5, 8], float)
type(test_array)

numpy.ndarray

In [5]:
a = [1, 2, 3, 4, 5]
b = [5,4,3,2,1]

In [6]:
a = np.array(a, int)
b = np.array(b, int)
a[0] is b[4] #그냥 배열이면 같아야하는데 nparray라 다름

False

In [7]:
test_array.dtype #전체 데이터 type, 8바이트
np.array([1, 2, 3], dtype = int)

array([1, 2, 3])

In [8]:
test_array.shape #어떻게 구성되어 있는지

(4,)

In [9]:
test_array.ndim #몇 차원인지

1

In [10]:
test_array.size #총 크기

4

### array shape
**array rank에 따라 불리는 이름이 있음**
- 0 : scalar
- 1 : vector
- 2 : matrix (열, 행 개수)
- 3 : 3-tensor (열, 행, 층)
- n : n-tensor

float32 면 32bits = 4byte, 만약 6개라면 24bytes 차지
int8 이면 8 bits = 1byte, 6bytes차지
float64라면 64bits = 8byte, 48bytes 차지

In [11]:
#reshape
## -1을 넣으면 size를 기반으로 row 개수 선정
test_matrix = [[1,2,3],[4,5,6]]

In [12]:
np.array(test_matrix).reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
np.array(test_matrix).reshape(2,-1,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [14]:
#flatten : 다차원 array를 1차원 array로 변환
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 5, 6])

In [15]:
#indexing 할 때 이차원 배열에서 [0,0]식으로 쓸 수 있음
test_exam = np.array(test_matrix)
test_exam[1,1]

5

In [16]:
#slicing 할 때, 행과 열 부분을 나눠서 가져갈 수 있음 (부분 집합 이용 가능)
test_exam[:,:2]

array([[1, 2],
       [4, 5]])

In [17]:
k = np.arange(100).reshape(10,10)
#array의 범위를 지정해서 값의 list 생성
#arrange(시작, 끝, step) step은 float도 가능
k

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [18]:
k[:, -1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [19]:
#건너 뛰는 것도 가능함
k[:,::2]

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [20]:
p = np.arange(1, 2, 0.5)
p

array([1. , 1.5])

In [21]:
#zeros : 0으로 가득찬 ndarray 생성
#np.zeros(shape, dtype, order)
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
#ones : 1로 가득찬 녀석 생성
#empty : shpae만 주어지고 비어진 ndarray생성 (초기화 안돼있음)
np.empty((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
#something_like : 기존 ndarray의 shape 크기 만큼 1, 0 또는 empty array 반환
np.ones_like(test_exam)

array([[1, 1, 1],
       [1, 1, 1]])

In [24]:
#identity 단위 행렬 생성 
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
#eye 대각선이 1인 행렬, k값의 시작 index 변경 가능
np.eye(3, 5, k = 1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [26]:
test_exam

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
#diag 대각 행렬의 값 추출 k는 start index
np.diag(test_exam, k = 1)

array([2, 6])

In [28]:
#random sampling으로 array 생성
#균등분포
np.random.uniform(0, 1, 10).reshape(2,5)

array([[0.08252939, 0.41894889, 0.33180906, 0.05086391, 0.02592039],
       [0.25049789, 0.81899891, 0.4588976 , 0.57118457, 0.2579569 ]])

In [29]:
#정규분포
np.random.normal(0, 1, 10).reshape(2, 5)

array([[-0.23962769, -0.45421702, -1.16051656, -0.05718792, -0.85384191],
       [ 1.98188013, -0.35962191,  0.60300472,  0.24258863, -0.90628277]])

In [30]:
#sum, dytype 가능 평균 : mean, 표준편차 : std
test_exam.sum(dtype=np.float32)

21.0

In [31]:
# axis : 기준이 되는 dimension 축
# (3,3,4) 일 때 axis = 0, 1, 2
test_exam.sum(axis = 1) #식으로 사용가능 > 행끼리 앞

array([ 6, 15])

In [39]:
#concatenate : numpy array를 합치는 함수
x = np.array([[1,2,3]])
y = np.array([[2,3,4]])
np.concatenate((x,y), axis=0) # 행 기준

array([[1, 2, 3],
       [2, 3, 4]])

기본적인 사칙 연산 지원함.
element-wise operation : array간 shape이 같을 때 일어나는 연산
### 기본 연산 dot

In [40]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

In [41]:
#transpose
test_a.transpose()
#or
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### broadcasting
shape이 다른 배열 간 연산을 지원하는 기능 (전부)

In [44]:
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3

In [45]:
test_matrix + scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

scalar - vector 외에도 vector - matrix 간의 연산도 지원

In [46]:
a = np.arange(10)
a < 4

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [47]:
# any 하나라도 조건에 만족한다면 true
np.any(a>5)

True

In [48]:
# all 모두 조건에 만족한다면 true
np.all(a<4)

False

In [49]:
# 배열의 크기가 동일할 때 비교 결과 반환
# logical_or / logical_not 존재
a = np.array([1,3,0], float)
np.logical_and(a > 0, a < 3) # and 조건

array([ True, False, False])

### np.where

In [50]:
#where(condition, TRUE, FALSE)
np.where(a > 0, 3, 2)

array([3, 3, 2])

In [51]:
#만족하는 인덱스 반환
a = np.arange(10)
np.where(a>5)

(array([6, 7, 8, 9]),)

In [53]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [54]:
np.isfinite(a)

array([ True, False, False])

### argmax & argmin
- array 내 최대값 또는 최소값 index 반환
- axis 기반 반환 가능
### argsort
- 내림차순
- argsort()[::-1] 오름차순

In [56]:
a = np.array([1,2,3,4,23])
a.argsort()[::-1]

array([4, 3, 2, 1, 0])

## timeit : jupyter에서 코드의 퍼포먼스 체크 함수
for < list comprehenshion < numpy

## boolean & fancy index

In [58]:
a > 3

array([False, False, False,  True,  True])

In [59]:
a = np.array([2,3,6,8], float)
b = np.array([0,0,1,3,2,1], int) #반드시 integer로 선언
a[b] #bracket index, b 배열의 값을 index로 하여 a의 값들을 추출함

array([2., 2., 3., 8., 6., 3.])

In [61]:
a.take(b) #take : bracket index // Matrix 형태의 데이터도 가능하다

array([2., 2., 3., 8., 6., 3.])

## 입출력 가능
np.loadtxt

np.savetxt