## 벡터와 행렬 

### 벡터의 노름
: 원점에서부터의 거리

노름의 종류에 따라 기하학적 성질이 달라짐

기계학습의 목적에 따라 달라지는 것


#### L1-norm
- 성분의 변화량의 절대값을 모두 더한 것
- L1-norm 상의 원은 마름모꼴 모양이 됨
#### L2-norm
- 유클리드 거리 계산 
- L2-norm 상의 원은 원 모양이 됨

In [2]:
import numpy as np

In [3]:
def l1_norm(x):
    x_norm = np.abs(x)
    x_norm = np.sum(x_norm)
    return x_norm

In [4]:
def l2_norm(x):
    x_norm = x*x
    x_norm = np.sum(x_norm)
    x_norm = np.sqrt(x_norm)
    return x_norm

#### 두 벡터 사이 거리 구하기
- 벡터의 뺄셈 이용
#### 두 벡터 사이의 각도 구하기
- L2-노름을 이용해야 함. 
- 유클리드 거리를 이용해서 제2코사인 법칙에 의해 각도를 계산할 수 있음. (다른 차원도 가능)
- 제 2 코사인 법칙이용
#### 내적
: 정사영된 벡터의 길이와 관련 있음
- 정사영된 벡터 길이 : proj(x) 는 코사인법칙에 의해 ||X||cos(theta)가 됨
- 내적은 이 정사영된 길이를 벡터 y의 길이 ||y||만큼 조정한 값

In [5]:
def angle(x,y):
    #inner은 내적 구하기
    v = np.inner(x,y) / (l2_norm(x) * l2_norm(y))
    theta = np.arccos(v)  #코사인 역을 곱해줌
    return theta

## 행렬
: 벡터를 원소로 가지는 2차원 배열
- numpy에서는 행이 기준
- n개의 행과 m개의 열 

- 공간에서 여러점들을 나타냄
- 행 벡터 xi는 i번째 데이터를 말함
#### 전치행렬
행과 열의 인덱스가 바뀐 행렬

In [16]:
# 행렬 곱셈 : i번째 행벡터와 j번째 열벡터 사이의 내적을 성분으로 가지는 행렬 계산
# x의 행의 개수와 y의 열의 개수가 같아야 함
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[1,2],[3,4],[5,6]])
y.resize(2,3)
y

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
#inner 수행시 x의 행의 개수가 y의 행의 개수와 같아야 함 (수학에서 말하는 내적과 다름)
np.inner(x,y)

array([[ 14,  32],
       [ 32,  77],
       [ 50, 122]])

행렬곱을 통해 벡터를 다른 차원의 공간으로 보낼 수 있음
### 역행렬
- 행과 열 숫자가 같아야 함
- 행렬식이 0이 아닌 경우에만 계산 가능
- 되돌아오게 하는게 가능함. A-1A = I 항등행렬 

In [23]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
x @ np.linalg.inv(x)

array([[ 0.,  0.,  0.],
       [-4.,  0., -4.],
       [ 0.,  0.,  0.]])

### 유사역행렬 
역행렬을 사용할 수 없다면 이용
- n >= m 이면 A+A = I가 성립
- n <= m 이면 AA+ = I가 성립 

선형회귀식을 찾을 수 있음. X*beta = y일 때 계수 beta를 찾음

- 연립방정식과 달리 행이 더 크므로 방정식으로 풀 수 없음.
- n>=인 경우, 데이터가 변수 개수보다 많거나 같아야 함.

차이를 최소화하는 y헷을 찾아야 함

In [36]:
y = np.array([[0, 1],
              [1, -1],
              [-2, 1]])

In [37]:
np.linalg.pinv(y)

array([[ 5.00000000e-01,  1.11022302e-16, -5.00000000e-01],
       [ 8.33333333e-01, -3.33333333e-01, -1.66666667e-01]])

In [38]:
np.linalg.pinv(y) @ y #순서 주의

array([[ 1.00000000e+00, -2.22044605e-16],
       [ 1.11022302e-16,  1.00000000e+00]])

In [42]:
X = np.arange(9).reshape(3,3)